// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDu-1dqgVciKcz9Hy3wzFP6CvvlbsC_GkM',
    appId: '1:812691823439:web:b55bab251f44593371c33a',
    messagingSenderId: '812691823439',
    projectId: 'gestticket-2bc62',
    authDomain: 'gestticket-2bc62.firebaseapp.com',
    storageBucket: 'gestticket-2bc62.appspot.com',
    measurementId: 'G-D6K0K4DXG1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcINwuqJJWV6pwNfmJmWukAoPvLu2vR00',
    appId: '1:812691823439:android:dd2c3ef1efebb1c271c33a',
    messagingSenderId: '812691823439',
    projectId: 'gestticket-2bc62',
    storageBucket: 'gestticket-2bc62.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_eATMgzQ1ln7oXpzxXpwxO0qovZ2VwBg',
    appId: '1:812691823439:ios:e2cafff01bccc94d71c33a',
    messagingSenderId: '812691823439',
    projectId: 'gestticket-2bc62',
    storageBucket: 'gestticket-2bc62.appspot.com',
    iosBundleId: 'com.example.ticket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_eATMgzQ1ln7oXpzxXpwxO0qovZ2VwBg',
    appId: '1:812691823439:ios:e2cafff01bccc94d71c33a',
    messagingSenderId: '812691823439',
    projectId: 'gestticket-2bc62',
    storageBucket: 'gestticket-2bc62.appspot.com',
    iosBundleId: 'com.example.ticket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDu-1dqgVciKcz9Hy3wzFP6CvvlbsC_GkM',
    appId: '1:812691823439:web:aced9976048bce8d71c33a',
    messagingSenderId: '812691823439',
    projectId: 'gestticket-2bc62',
    authDomain: 'gestticket-2bc62.firebaseapp.com',
    storageBucket: 'gestticket-2bc62.appspot.com',
    measurementId: 'G-6TBC4PLHHM',
  );

}